[build]
  publish = "out"  # Adjust this to match your build output folder (for example, "out" for Next.js or "public" for static sites)

[[redirects]]
  from = "/#invite_token=:invite_token"
  to = "/admin/#invite_token=:invite_token"
  status = 200
  force = true
