[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/#invite_token=:invite_token"
  to = "/admin/#invite_token=:invite_token"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    enableMiddleware = true
    generateFunctions = false  # Important for Netlify Forms to work

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
