backend:
  name: git-gateway
  branch: main  # Or your working branch

media_library:
  name: cloudinary
  config:
    cloud_name: "dcrue4vr6"  # Your Cloudinary cloud name
    api_key: "411427416161613"  # Your Cloudinary API key
    api_secret: "IJHHE-g01BgD_TYU-RuwuUip_ug"  # Your Cloudinary API secret

media_folder: "public/images/uploads"  # Local path in your repository (not used for string input)
public_folder: "/images/uploads"  # The public URL path for accessing media on your site

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    slug: "{{slugId}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true, hint: "Enter the title of the blog post." }
      - { label: "Slug ID", name: "slugId", widget: "string", required: true, hint: "SEO-friendly URL for the post." }
      - { label: "Date", name: "date", widget: "string", required: true, hint: "Publication date in MM/DD/YYYY format." }
      - { label: "Section", name: "section", widget: "select", options: ["how-to", "home-improvement", "seasonal-home-care"], required: true, hint: "Select the blog section this post belongs to." }  # No quotes here
      - { label: "Body", name: "body", widget: "markdown", required: true, hint: "Main content of the post in Markdown format." }
      - { label: "Image", name: "image", widget: "string", required: true, hint: "URL of the featured image." }
      - { label: "Meta Title", name: "metaTitle", widget: "string", required: true, hint: "Title for search engine results." }
      - { label: "Meta Description", name: "metaDescription", widget: "text", required: true, hint: "Brief description of the post." }
      - { label: "OG Image", name: "ogImage", widget: "string", required: true, hint: "Open Graph image URL for social media sharing." }
      - { label: "Image Alt Text", name: "altText", widget: "string", required: true, hint: "Describe the image for accessibility." }
      - { label: "Keywords", name: "keywords", widget: "list", field: { label: "Keyword", name: "keyword", widget: "string" }, required: true, hint: "Main keywords for this post." }
